'use client'
import { useEffect, useState } from 'react'
function today(){return new Date().toISOString().slice(0,10)}
export default function ContractorPortalClient(){
  const [email,setEmail]=useState(''),[pin,setPin]=useState(''),[contractor,setContractor]=useState(null),[jobs,setJobs]=useState([]),[msg,setMsg]=useState(''),[notes,setNotes]=useState({})
  async function login(){setMsg('Checking login...');const r=await fetch('/api/contractor-portal/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,pin})});const j=await r.json().catch(()=>({}));if(j.ok){setContractor(j.contractor);setMsg('');}else setMsg(j.error||'Login failed')}
  async function loadJobs(){if(!contractor?.id)return;const r=await fetch('/api/contractor-portal/jobs?contractorId='+encodeURIComponent(contractor.id)+'&contractorName='+encodeURIComponent(contractor.name||''),{cache:'no-store'});const j=await r.json().catch(()=>({}));if(j.ok)setJobs(j.jobs||[]);else setMsg(j.error||'Could not load jobs')}
  useEffect(()=>{loadJobs()},[contractor?.id])
  async function updateJob(job,patch){const r=await fetch('/api/contractor-portal/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contractorId:contractor.id,contractorName:contractor.name,jobId:job.id,...patch})});const j=await r.json().catch(()=>({}));if(j.ok){setMsg('Job updated.');loadJobs()}else setMsg(j.error||'Update failed')}
  async function uploadPhoto(job,file){if(!file)return;setMsg('Uploading photo...');const fd=new FormData();fd.append('contractorId',contractor.id);fd.append('contractorName',contractor.name||'');fd.append('jobId',job.id);fd.append('file',file);const r=await fetch('/api/contractor-portal/upload',{method:'POST',body:fd});const j=await r.json().catch(()=>({}));if(j.ok){await updateJob(job,{afterPhoto:j.url,notes:notes[j.id]||job.contractorNotes||'',status:job.status})}else setMsg(j.error||'Upload failed')}
  if(!contractor) return <section className="section"><div className="container narrow"><article className="card"><h2>Contractor Login</h2><p>Use the email and PIN Yard Loop gave you.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN" type="password"/><button onClick={login}>Log In</button>{msg&&<p>{msg}</p>}</article></div></section>
  return <section className="section"><div className="container"><div className="between"><div><h2>Welcome, {contractor.name}</h2><p>{jobs.length} assigned job{jobs.length===1?'':'s'}</p></div><button onClick={()=>{setContractor(null);setJobs([])}}>Log out</button></div>{msg&&<p className="notice">{msg}</p>}<div className="grid2">{jobs.length?jobs.map(job=><article className="card" key={job.id}><h3>{job.service||'Service'}</h3><p><b>Customer:</b> {job.customerName||'—'}</p><p><b>Address:</b> {job.address||'—'}</p><p><b>Due:</b> {job.due||job.scheduledDate||today()}</p><p><b>Status:</b> {job.status||'Assigned'}</p>{job.address&&<p><a target="_blank" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(job.address)}`}>Open in Maps</a></p>}<textarea value={notes[job.id]??job.contractorNotes??''} onChange={e=>setNotes({...notes,[job.id]:e.target.value})} placeholder="Gate notes, access notes, completion notes"/><label className="buttonLike">Upload after photo<input style={{display:'none'}} type="file" accept="image/*" onChange={e=>uploadPhoto(job,e.target.files?.[0])}/></label>{(job.afterPhoto||job.afterPhotos?.[0])&&<p><a target="_blank" href={job.afterPhoto||job.afterPhotos?.[0]}>View uploaded photo</a></p>}<div className="rowBtns"><button onClick={()=>updateJob(job,{status:'In Progress',notes:notes[job.id]||job.contractorNotes||''})}>Start</button><button onClick={()=>updateJob(job,{status:'Completed',notes:notes[job.id]||job.contractorNotes||''})}>Mark Complete</button></div></article>):<article className="card"><h3>No jobs assigned</h3><p>Assigned Yard Loop work will show up here.</p></article>}</div></div></section>
}
