'use client'
import { useEffect, useState } from 'react'
function money(n){return `$${Math.round(Number(n||0)).toLocaleString()}`}
export default function CustomerPortalClient({initialToken=''}){
  const [email,setEmail]=useState(''),[token,setToken]=useState(initialToken),[msg,setMsg]=useState(''),[data,setData]=useState(null)
  const [request,setRequest]=useState({type:'Pause Service',service:'',startDate:'',endDate:'',reason:''})
  async function requestLink(){const r=await fetch('/api/customer-portal/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}); const j=await r.json().catch(()=>({})); setMsg(j.message||j.error||'Check your email.')}
  async function load(){if(!token)return; const r=await fetch('/api/customer-portal/data?token='+encodeURIComponent(token),{cache:'no-store'}); const j=await r.json().catch(()=>({})); if(j.ok)setData(j); else setMsg(j.error||'Portal link not valid')}
  async function openStripePortal(){setMsg('Opening secure Stripe billing portal...');const r=await fetch('/api/customer-portal/stripe-portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}); const j=await r.json().catch(()=>({})); if(j.url) window.location.href=j.url; else setMsg(j.error||'Stripe portal is not available yet.')}
  async function submitRequest(){const r=await fetch('/api/customer-portal/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...request})}); const j=await r.json().catch(()=>({})); setMsg(j.ok?'Request sent to Yard Loop.':j.error||'Request failed')}
  useEffect(()=>{load()},[token])
  if(data?.customer){const c=data.customer; return <section className="section"><div className="container"><h1>My Yard Loop Plan</h1>{msg&&<p className="notice">{msg}</p>}<div className="grid2"><article className="card"><h2>{c.name}</h2><p><b>Address:</b> {c.address}</p><p><b>Monthly:</b> {money(c.monthly)}</p><p><b>Status:</b> {c.status}</p><p><b>Renewal:</b> {c.renewalDate||'—'}</p><button onClick={openStripePortal}>Update Payment Method</button></article><article className="card"><h2>Services</h2><ul>{(c.selectedServices||[]).map(s=><li key={s}>{s}</li>)}</ul></article></div><article className="card"><h2>Upcoming / Recent Jobs</h2>{(data.jobs||[]).length?data.jobs.map(j=><p key={j.id}><b>{j.service}</b> — {j.status} — {j.due||j.completedAt||'No date yet'}</p>):<p>No jobs listed yet.</p>}</article><article className="card"><h2>Payment History</h2>{(data.paymentHistory||[]).length?data.paymentHistory.map(p=><p key={p.id}><b>{money(p.amount)}</b> — {p.status} — {String(p.date||'').slice(0,10)}</p>):<p>No Stripe payment history is listed yet.</p>}<p><b>Lifetime value:</b> {money(data.lifetimeValue||0)}</p></article><article className="card"><h2>Pause / Change / Cancel Request</h2><label>Request type<select value={request.type} onChange={e=>setRequest({...request,type:e.target.value})}><option>Pause Service</option><option>Change Services</option><option>Cancel Service</option><option>General Question</option></select></label><input value={request.service} onChange={e=>setRequest({...request,service:e.target.value})} placeholder="Service, if applicable"/><div className="grid2"><input type="date" value={request.startDate} onChange={e=>setRequest({...request,startDate:e.target.value})}/><input type="date" value={request.endDate} onChange={e=>setRequest({...request,endDate:e.target.value})}/></div><textarea value={request.reason} onChange={e=>setRequest({...request,reason:e.target.value})} placeholder="Tell Yard Loop what you need"/><button onClick={submitRequest}>Send Request</button><p>For urgent issues, contact {data.settings?.companyEmail||'info@yard-loop.com'}.</p></article></div></section>}
  return <section className="section"><div className="container narrow"><h1>Customer Portal</h1><p>Enter your email and Yard Loop will send a secure portal link.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address"/><button onClick={requestLink}>Send Portal Link</button>{msg&&<p>{msg}</p>}</div></section>
}
