'use client'
import { useState } from 'react'
import '../../style.css'

const envVars=['JOBBER_CLIENT_ID','JOBBER_CLIENT_SECRET','JOBBER_REDIRECT_URL','JOBBER_ACCESS_TOKEN','JOBBER_REFRESH_TOKEN','JOBBER_WEBHOOK_SECRET']
const syncToggles=['Clients','Properties','Requests','Quotes','Jobs','Scheduled Items','Invoices','Payment Status']
const webhookTopics=['APP_CONNECT','APP_DISCONNECT','CLIENT_CREATE','CLIENT_UPDATE','PROPERTY_CREATE','PROPERTY_UPDATE','REQUEST_CREATE','REQUEST_UPDATE','QUOTE_CREATE','QUOTE_UPDATE','JOB_CREATE','JOB_UPDATE','JOB_CLOSED','INVOICE_CREATE','INVOICE_UPDATE','PAYMENT_CREATE','PAYMENT_UPDATE']

export default function JobberAdmin(){
  const[password,setPassword]=useState('')
  const[msg,setMsg]=useState('')
  const[status,setStatus]=useState(null)
  const[toggles,setToggles]=useState(Object.fromEntries(syncToggles.map(x=>[x,true])))
  const callback='https://www.yard-loop.com/api/jobber/callback'
  const webhook='https://www.yard-loop.com/api/jobber/webhooks'
  const manage='https://www.yard-loop.com/admin/jobber'
  const headers=()=>({'x-admin-password':password})
  async function check(){try{const r=await fetch('/api/jobber/status',{headers:headers(),cache:'no-store'});const j=await r.json();setStatus(j);setMsg(r.ok?'Status loaded':'Status failed: '+(j.error||'check password'))}catch(e){setMsg(e.message)}}
  async function connect(){try{const r=await fetch('/api/jobber/connect',{headers:headers(),cache:'no-store'});const j=await r.json();if(j.authorizeUrl){location.href=j.authorizeUrl;return}setMsg(j.error||'Could not create Jobber connect URL')}catch(e){setMsg(e.message)}}
  async function test(){try{const r=await fetch('/api/jobber/test',{method:'POST',headers:headers()});const j=await r.json();setMsg(r.ok&&j.ok?'Jobber test passed: '+(j.result?.data?.account?.name||'connected'):'Jobber test failed: '+(j.error||'check credentials'))}catch(e){setMsg(e.message)}}
  return <main className="ylCrm"><section className="ylMain" style={{marginLeft:0,maxWidth:1100,margin:'0 auto'}}><h1>Jobber Admin</h1>{msg&&<div className="ylMsg">{msg}</div>}<section className="ylCard"><h2>Configured Jobber Developer URLs</h2><p><b>Callback URL:</b> {callback}</p><p><b>Webhook URL:</b> {webhook}</p><p><b>Manage App URL:</b> {manage}</p><p className="ylHint">These match the URLs entered in Jobber Developer. Keep them exact.</p></section><section className="ylCard"><h2>Secure Connection</h2><label className="ylField"><span>Admin / cloud password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><div className="ylActions"><button onClick={check}>Check Status</button><button className="ylPrimary" onClick={connect}>Connect Jobber OAuth</button><button onClick={test}>Test Jobber</button></div>{status&&<pre style={{whiteSpace:'pre-wrap',background:'#f6faf2',padding:12,borderRadius:12}}>{JSON.stringify(status,null,2)}</pre>}<p className="ylHint">Do not paste secrets into this page. Add them in Vercel Environment Variables only.</p></section><section className="ylCard"><h2>Vercel Environment Variables Needed</h2>{envVars.map(v=><p className="ylLine" key={v}><b>{v}</b><small>Add in Vercel → Project → Settings → Environment Variables.</small></p>)}</section><section className="ylCard"><h2>Sync Toggles</h2>{syncToggles.map(t=><label className="ylCheck" key={t}><input type="checkbox" checked={!!toggles[t]} onChange={e=>setToggles({...toggles,[t]:e.target.checked})}/>{t}</label>)}<p className="ylHint">These are readiness toggles for the CRM flow. Final live sync still depends on the Jobber API field mapping tested with your account.</p></section><section className="ylCard"><h2>Webhook Topics Configured</h2><div className="ylPills">{webhookTopics.map(t=><span className="ylBadge green" key={t}>{t}</span>)}</div></section><section className="ylCard"><h2>Error Log</h2><p className="ylHint">Jobber sync failures appear inside the CRM activity feed and failed record warnings. This page gives the owner a single place to check connection status.</p></section><CrmAdminMiniStyles/></section></main>
}
function CrmAdminMiniStyles(){return <style jsx global>{`.ylCrm{min-height:100vh;background:#f3f7ef;color:#102033;font-family:Arial,Helvetica,sans-serif}.ylMain{padding:24px}.ylCard{background:white;border:1px solid #dfe9d9;border-radius:18px;padding:18px;margin-bottom:16px}.ylField{display:block;margin-bottom:12px}.ylField span{display:block;font-size:12px;font-weight:900;color:#52677a;margin-bottom:4px}.ylField input{width:100%;border:1px solid #d1dde8;border-radius:12px;padding:10px}.ylActions{display:flex;gap:8px;flex-wrap:wrap}.ylActions button{border:1px solid #cbd8c5;border-radius:12px;background:white;color:#0d253f;font-weight:900;padding:10px 12px}.ylPrimary{background:#49a942!important;color:white!important}.ylMsg{background:#0d253f;color:white;border-radius:14px;padding:12px 14px;margin-bottom:14px;font-weight:800}.ylLine{border-bottom:1px solid #edf2ea;padding:10px 0}.ylLine b,.ylLine small{display:block}.ylHint{font-size:13px;color:#5f7182}.ylCheck{display:flex;gap:8px;font-weight:800;margin:10px 0}.ylPills{display:flex;gap:8px;flex-wrap:wrap}.ylBadge{border-radius:999px;padding:6px 10px;font-size:12px;font-weight:900}.ylBadge.green{background:#e9f8e5;color:#256d22}`}</style>}
